spring:
  main:
    banner-mode: 'off'
management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      access: READ_ONLY    
    info:
      access: READ_ONLY