services:
  sgw.service.local:
    build:
      context: ./devlorean-sgw
    ports:
      - 80:80
    environment:
      - BUCKET_NAME=346929044083-bucket
      - AWS_REGION=ap-northeast-1
      - WEB_HOST=web.service.local
      - WEB_PORT=3000
      # - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost/health"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  sig.service.local:
    build:
      context: ./devlorean-sig
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "nc -nz http://localhost:8080/"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  web.service.local:
    build:
      context: ./devlorean-web
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3000/health"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s