services:
  sgw.service.local:
    build:
      context: ./devlorean-sgw
    ports:
      - 80:10000
    environment:
      - CDS_HOST=cds.service.local
      - CDS_PORT=80
      - WEB_HOST=web.service.local
      - WEB_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/ready"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
  cds.service.local:
    image: public.ecr.aws/docker/library/nginx:mainline-bookworm-perl
    volumes:
      - ./devlorean-web/.output/public:/usr/share/nginx/html:ro
  web.service.local:
    build:
      context: ./devlorean-web
    environment:
      - NUXT_API_BASE_URL=http://api.service.local:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
  api.service.local:
    build:
      context: ./devlorean-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s