services:
  web-gateway:
    build:
      context: ./devlorean-gw
      args:
        - public_cluster_hostname=public.nuxt
        - server_cluster_hostname=server.nuxt
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/ready"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s
  server.nuxt:
    build:
      context: ./devlorean-web
      dockerfile: Dockerfile.server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s
  public.nuxt:
    build:
      context: ./devlorean-web
      dockerfile: Dockerfile.public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s
