FROM public.ecr.aws/docker/library/node:current-bullseye-slim

RUN apt-get update -y && apt-get install -y curl
COPY ./.output/server/ /server

EXPOSE 3000
ENTRYPOINT [ "node" ]
CMD [ "/server/index.mjs" ]